version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: prompt-studio-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-prompt_studio}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -d ${POSTGRES_DB:-prompt_studio} -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres-data:
